const API_BASE="https://www.omdbapi.com/";
const STORAGE_KEY="barakah_techlabs_omdb_api_key";
const searchForm=document.querySelector("#searchForm"),searchInput=document.querySelector("#searchInput"),searchButton=document.querySelector("#searchButton"),movieGrid=document.querySelector("#movieGrid"),statusBox=document.querySelector("#status"),resultsTitle=document.querySelector("#resultsTitle"),resultCount=document.querySelector("#resultCount"),apiKeyModal=document.querySelector("#apiKeyModal"),apiKeyForm=document.querySelector("#apiKeyForm"),apiKeyInput=document.querySelector("#apiKeyInput"),apiKeyButton=document.querySelector("#apiKeyButton"),closeModal=document.querySelector("#closeModal");
function getApiKey(){return localStorage.getItem(STORAGE_KEY)||""}
function showStatus(message,type=""){statusBox.textContent=message;statusBox.className="status"+(type?" "+type:"")}
function clearStatus(){statusBox.textContent="";statusBox.className="status hidden"}
function setLoading(loading){searchButton.disabled=loading;searchButton.querySelector("span").textContent=loading?"Searching...":"Search"}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,function(char){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]})}
function renderMovies(movies){movieGrid.innerHTML=movies.map(function(movie){const poster=movie.Poster&&movie.Poster!=="N/A"?'<img class="poster" src="'+escapeHtml(movie.Poster)+'" alt="'+escapeHtml(movie.Title)+' poster" loading="lazy">':'<div class="poster-fallback">No poster available</div>';return'<article class="movie-card">'+poster+'<div class="movie-info"><h3>'+escapeHtml(movie.Title)+'</h3><p class="movie-meta">'+escapeHtml(movie.Year)+' • '+escapeHtml(movie.Type)+'</p></div></article>'}).join("");resultCount.textContent=movies.length+" result"+(movies.length===1?"":"s")}
async function searchMovies(title){const apiKey=getApiKey();if(!apiKey){openApiKeyModal();return}clearStatus();movieGrid.innerHTML="";resultCount.textContent="";resultsTitle.textContent="Results for “"+title+"”";setLoading(true);try{const url=new URL(API_BASE);url.searchParams.set("apikey",apiKey);url.searchParams.set("s",title);url.searchParams.set("type","movie");const response=await fetch(url);if(!response.ok)throw new Error("Request failed with status "+response.status);const data=await response.json();if(data.Response==="False")throw new Error(data.Error||"No movies found.");if(!Array.isArray(data.Search)||data.Search.length===0)throw new Error("No movies found for that search.");renderMovies(data.Search)}catch(error){movieGrid.innerHTML="";resultCount.textContent="";showStatus(error instanceof TypeError?"Network error. Please check your internet connection and try again.":error.message,"error")}finally{setLoading(false)}}
function openApiKeyModal(){apiKeyInput.value=getApiKey();apiKeyModal.classList.remove("hidden");apiKeyInput.focus()}
function closeApiKeyModal(){apiKeyModal.classList.add("hidden")}
searchForm.addEventListener("submit",function(event){event.preventDefault();const title=searchInput.value.trim();if(title.length<2){showStatus("Please enter at least 2 characters.","error");searchInput.focus();return}searchMovies(title)});
apiKeyForm.addEventListener("submit",function(event){event.preventDefault();const key=apiKeyInput.value.trim();if(!key)return;localStorage.setItem(STORAGE_KEY,key);closeApiKeyModal();showStatus("API key saved. You can now search for movies.")});
apiKeyButton.addEventListener("click",openApiKeyModal);closeModal.addEventListener("click",closeApiKeyModal);apiKeyModal.addEventListener("click",function(event){if(event.target===apiKeyModal)closeApiKeyModal()});document.addEventListener("keydown",function(event){if(event.key==="Escape")closeApiKeyModal()});
if(!getApiKey())showStatus("Add your free OMDb API key using the “API Key” button to start searching.");